-- MySQL Script generated by MySQL Workbench
-- Wed Feb  5 13:50:14 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Pokedex
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Pokedex
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Pokedex` DEFAULT CHARACTER SET utf8 ;
USE `Pokedex` ;

-- -----------------------------------------------------
-- Table `Pokedex`.`Type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pokedex`.`Type` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `image` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Pokedex`.`Capacity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pokedex`.`Capacity` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `power` INT(11) NULL DEFAULT NULL,
  `Type_id` INT(11) NOT NULL,
  `category` VARCHAR(45) NULL DEFAULT NULL,
  `pp` DECIMAL(10,0) NULL DEFAULT NULL,
  `accuracy` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Capacity_Type1_idx` (`Type_id` ASC) VISIBLE,
  CONSTRAINT `fk_Capacity_Type1`
    FOREIGN KEY (`Type_id`)
    REFERENCES `Pokedex`.`Type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Pokedex`.`Talent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pokedex`.`Talent` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` TINYTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Pokedex`.`Pokemon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pokedex`.`Pokemon` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `number` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `artwork` VARCHAR(255) NOT NULL,
  `sprite` VARCHAR(255) NOT NULL,
  `spriteShiny` VARCHAR(255) NOT NULL,
  `description` TINYTEXT NOT NULL,
  `talent1` INT(11) NOT NULL,
  `talent2` INT(11) NULL,
  `talent3` INT(11) NULL,
  `type1` INT(11) NOT NULL,
  `type2` INT(11) NULL,
  `evolution` INT(11) NULL,
  `prevolution` INT(11) NULL,
  `hp` INT NOT NULL,
  `atk` INT NOT NULL,
  `def` INT NOT NULL,
  `atkspe` INT NOT NULL,
  `defspe` INT NOT NULL,
  `speed` INT NULL,
  `special` INT NULL,
  `Pokemoncol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Pokemon_Talent1_idx` (`talent1` ASC),
  INDEX `fk_Pokemon_Talent2_idx` (`talent2` ASC),
  INDEX `fk_Pokemon_Talent3_idx` (`talent3` ASC),
  INDEX `fk_Pokemon_Type1_idx` (`type1` ASC),
  INDEX `fk_Pokemon_Type2_idx` (`type2` ASC),
  INDEX `fk_Pokemon_Pokemon1_idx` (`evolution` ASC),
  INDEX `fk_Pokemon_Pokemon2_idx` (`prevolution` ASC),
  CONSTRAINT `fk_Pokemon_Talent1`
    FOREIGN KEY (`talent1`)
    REFERENCES `Pokedex`.`Talent` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pokemon_Talent2`
    FOREIGN KEY (`talent2`)
    REFERENCES `Pokedex`.`Talent` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pokemon_Talent3`
    FOREIGN KEY (`talent3`)
    REFERENCES `Pokedex`.`Talent` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pokemon_Type1`
    FOREIGN KEY (`type1`)
    REFERENCES `Pokedex`.`Type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pokemon_Type2`
    FOREIGN KEY (`type2`)
    REFERENCES `Pokedex`.`Type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pokemon_Pokemon1`
    FOREIGN KEY (`evolution`)
    REFERENCES `Pokedex`.`Pokemon` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pokemon_Pokemon2`
    FOREIGN KEY (`prevolution`)
    REFERENCES `Pokedex`.`Pokemon` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Pokedex`.`PokemonCheckpoint`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pokedex`.`PokemonCheckpoint` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `number` DECIMAL(10,0) NOT NULL,
  `image` VARCHAR(254) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Pokedex`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pokedex`.`User` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` LONGTEXT NULL DEFAULT NULL,
  `role` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Pokedex`.`Team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pokedex`.`Team` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `Pokemon1` INT(11) NOT NULL,
  `Pokemon2` INT(11) NOT NULL,
  `Pokemon3` INT(11) NOT NULL,
  `Pokemon4` INT(11) NOT NULL,
  `Pokemon5` INT(11) NOT NULL,
  `Pokemon6` INT(11) NOT NULL,
  `User_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Team_PokemonCheckpoint1_idx` (`Pokemon1` ASC),
  INDEX `fk_Team_PokemonCheckpoint2_idx` (`Pokemon2` ASC),
  INDEX `fk_Team_PokemonCheckpoint3_idx` (`Pokemon3` ASC) ,
  INDEX `fk_Team_PokemonCheckpoint4_idx` (`Pokemon4` ASC) ,
  INDEX `fk_Team_PokemonCheckpoint5_idx` (`Pokemon5` ASC) ,
  INDEX `fk_Team_PokemonCheckpoint6_idx` (`Pokemon6` ASC) ,
  INDEX `fk_Team_User1_idx` (`User_id` ASC) VISIBLE,
  CONSTRAINT `fk_Team_PokemonCheckpoint1`
    FOREIGN KEY (`Pokemon1`)
    REFERENCES `Pokedex`.`PokemonCheckpoint` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Team_PokemonCheckpoint2`
    FOREIGN KEY (`Pokemon2`)
    REFERENCES `Pokedex`.`PokemonCheckpoint` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Team_PokemonCheckpoint3`
    FOREIGN KEY (`Pokemon3`)
    REFERENCES `Pokedex`.`PokemonCheckpoint` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Team_PokemonCheckpoint4`
    FOREIGN KEY (`Pokemon4`)
    REFERENCES `Pokedex`.`PokemonCheckpoint` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Team_PokemonCheckpoint5`
    FOREIGN KEY (`Pokemon5`)
    REFERENCES `Pokedex`.`PokemonCheckpoint` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Team_PokemonCheckpoint6`
    FOREIGN KEY (`Pokemon6`)
    REFERENCES `Pokedex`.`PokemonCheckpoint` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Team_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `Pokedex`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 27
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Pokedex`.`Pokemon_has_Capacity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pokedex`.`Pokemon_has_Capacity` (
  `Pokemon_id` INT(11) NOT NULL,
  `Capacity_id` INT(11) NOT NULL,
  PRIMARY KEY (`Pokemon_id`, `Capacity_id`),
  INDEX `fk_Pokemon_has_Capacity_Capacity1_idx` (`Capacity_id` ASC) ,
  INDEX `fk_Pokemon_has_Capacity_Pokemon1_idx` (`Pokemon_id` ASC) ,
  CONSTRAINT `fk_Pokemon_has_Capacity_Pokemon1`
    FOREIGN KEY (`Pokemon_id`)
    REFERENCES `Pokedex`.`Pokemon` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pokemon_has_Capacity_Capacity1`
    FOREIGN KEY (`Capacity_id`)
    REFERENCES `Pokedex`.`Capacity` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
